name: bugun_juma
description: "Bismillah."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  weekly_date_picker: ^1.4.2
  step_progress_indicator: ^1.0.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  prayers_times: ^0.0.6
  intl: ^0.17.0
  adhan_dart: any
  geolocator: ^7.6.2
  sensors_plus: ^2.0.1
  flutter_lints: ^2.0.1
  permission_handler: ^11.3.0
  flutter_islamic_icons: ^1.0.2
  audioplayers: ^4.1.0
  vibration:
  hijri: ^3.0.0
  confetti: ^0.6.0
  http: ^0.13.4
  path_provider: ^2.0.2
  flutter_media_downloader:
  syncfusion_flutter_datepicker: ^21.1.37
  sqflite: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/imgs/
   - assets/audios/
   - assets/imgs/alderdalog/
   - assets/imgs/tahorat/
   - assets/imgs/tayammum/
   - assets/imgs/gusul/
   - assets/imgs/sheyx/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
