class IslamicQuotes {
  String auth;
  String description;

  IslamicQuotes(this.auth, this.description);

  static List<IslamicQuotes> quotesData = [
    IslamicQuotes("Hasan al-Basriy",
        """“Ko‘p ibodat qilaman deb mag‘rurlanmagin. Iblisning ming yillab qilgan ibodati nima bo‘lganini ko‘rib fikr qilgin.” """),
    IslamicQuotes("Fuzayl ibn Iyoz",
        """“Tavoze’lik – bu haqiqatni garchi yosh boladan, o‘qimagan yoki johil odamdan eshitganda ham uni qabul qilishdir”. """),
    IslamicQuotes("Ali ibn Abu Tolib",
        """“Baraka shukronalikka bog‘liq, shukronalik yanada ko‘proq baraka olib keladi. U ikkisi o‘zaro bir-biriga bog‘langandir”. """),
    IslamicQuotes("Ahmad ibn Hanbal",
        """“Alloh sen yaxshi ko‘rgan narsalarni muntazam berib turishini orzu qilsang, sen ham Unga maqbul bo‘ladigan amallarni muntazam qilib yurgin”."""),
    IslamicQuotes("Sufyon Savriy",
        """“Bir inson ilm o‘rganmoqni istasa u uch bosqichni bosib o‘tadi:
1. Kekkayib ketadi;
2. Kamtar bo‘lib qoladi;
3. Hech narsa bilmasligini tushunib yetadi.”"""),
    IslamicQuotes("Umar ibn Xattob",
        """“Ba’zan o‘tmishi eng yomon bo‘lgan odamlar o‘zlariga eng yaxshi kelajakni yaratadilar”."""),
    IslamicQuotes("Ibn Atoulloh Iskandariy",
        """“Allohni yo‘qotgan odam nimani topadi?! Aksincha, Allohni topgan odam nimani yo‘qotadi?”"""),
    IslamicQuotes("Imom Shofeiy",
        """“Agar inson yetarlicha dono bo‘lsa, o‘zining qilgan gunohlarini o‘ylashi boshqa odamlar qilgan gunoh ishlarni ko‘rishdan diqqatini chalg‘itadi”."""),
    IslamicQuotes("Abu Bakr Siddiq",
        """O‘zgalarning dard-alamini o‘ziga olib uni yengillatish bu muruvvatning eng oliy mohiyatidir”.
"""),
    IslamicQuotes("Imom G‘azzoliy",
        """“Sevgingga erishmog‘ing uchun avval yomon ko‘rgan narsangga sabr qilishni o‘rganishing zarur.”"""),
    IslamicQuotes("Ibn Qayyum",
        """“Kimdir menga g‘azab qilib xafa qilsa, Alloh uni menga itoatkorlikni o‘rgatish uchun yuboribdi deb o‘ylayman”."""),
    IslamicQuotes("Ibn Sirin",
        """“Oramizdagi eng ko‘p gunohi borlar boshqalarning gunohlarini gapirib vaqtini o‘tkazadiganlardir”."""),
    IslamicQuotes("Usmon ibn Affon",
        """“Hayotingning maqsadi bo‘lsin, unga yetishish uchun butun imkoniyatingdan foydalangin, albatta muvaffaqiyatga erishasan”."""),
    IslamicQuotes("Hasan Basriy",
        """“Mo‘minning eng yaxshi xislati — uning kechirimli ekanligidir”."""),
    IslamicQuotes("Umar ibn Xattob",
        """“Har qanday miqdordagi gunoh o‘tmishni o‘zgartira olmaganidek, har qanday taraddud ham kelajakni o‘zgartira olmaydi”."""),
    IslamicQuotes("Ibn Atoulloh Iskandariy",
        """“Qanday qilib behuda orzu-havaslarga bog‘langan ko‘ngil Allohning huzuriga safar qilsin?! Qanday qilib kasofat g‘aflatidan poklanmay vujudi ilohiyga mushtoq bo‘lsin?! Qanday qilib qilgan gunohlariga iqror bo‘lmay nozik sirlarni tushunishga umid qilsin?!”"""),
    IslamicQuotes("Umar ibn Xattob",
        """“Dunyoning azizligi mol bilan, oxiratning azizligi solih amallar bilan.”"""),
    IslamicQuotes("Hasan Basriy",
        """“Dunyo kezib oxiratini topganni ko‘rmadik, lekin oxiratini qidirib, dunyosini topganlarni ko‘rdik.”"""),
    IslamicQuotes("Umar ibn Xattob",
        """“Dunyosini tark etib, faqat oxirati uchun amal qilgan odam ham yoki oxiratini tark etib faqat dunyosi uchun amal qilgan odam ham sizlarning yaxshilaringiz emas. Balki unisiniyam, bunisiniyam ushlagan odam yaxshilaringizdir.”"""),
    IslamicQuotes("Yahyo ibn Maoz",
        """“Dunyo shaytonning do‘konidir, undan biron narsa o‘g‘irlamaki, shayton uni olishga kelib, sening dodingni bermasin.”"""),
    IslamicQuotes(
        "Molik ibn Dinor", """“Havoyi nafsga berilib yashashdan saqlaning.”"""),
    IslamicQuotes("Zahiriddin Muhammad Bobur",
        """“Nega nafsingga bo‘lursan tobe’,\nNega umringni qilursan zoe?!”"""),
    IslamicQuotes("Jaloliddin Rumiy",
        """“Ey inson, qo‘llaringdagi zanjirlarni yech, hur bo‘l! Tokay oltinning, zeru zabarning asiri bo‘lasan?!”"""),
    IslamicQuotes("Hasan Basriy",
        """“Kim senga gap yetkazsa, bilginki, sening gapingni ham boshqaga yetkazadi.”"""),
    IslamicQuotes("Alisher Navoiy",
        """“Jahl ahli bilan kimki ulfat bo‘lg‘ay,\nUl ulfat ichra yuz ming kulfat bo‘lg‘ay.”"""),
    IslamicQuotes("Imom Shofe’iy",
        """“Qilich va nayza bilan hosil bo‘lmagan ko‘p ishlar yumshoqlik, muloyimlik bilan hosil bo‘ladi. G’azab keltirgan zarar g‘azablangan kishining o‘ziga qaytar.”"""),
    IslamicQuotes("Abu Bakr Siddiq",
        """“Kimki qabrga tayyorgarliksiz kirsa, go’yo dengizga kemasiz chiqqandek bo’ladi.”"""),
    IslamicQuotes("Imom Shofe’iy",
        """“Dinda ko’z-ko’z qilish qalbni qotiradi va adovatni keltirib chiqaradi.”"""),
    IslamicQuotes("Ibn Ma’sud",
        """“Alloh taolo Islomdan nasiba olgan kishini Islomdan benasib kishi kabi qilib qo’ymaydi.”"""),
    IslamicQuotes("Hasan Basriy",
        """“Fikr-yaxshilik va yomonliklaringni ko’rsatadigan oina.”"""),
    IslamicQuotes("Husayn ibn Ali",
        """“So‘ralmasidan bergan haqiqiy saxiy odam, qasos olishga qodir bo‘laturib, avf etgan haqiqiy mard odam.”"""),
    IslamicQuotes(
        "Hasan Basriy", """“Pulni o‘ylab sarf qilmoq yarim foydadir.”"""),
    IslamicQuotes("Muhammad Siddiq Rushdiy",
        """“O’zing muhtoj bo‘laturib, saxiylik qilaman dema.”"""),
    IslamicQuotes("Jaloliddin Rumiy",
        """“Go‘zallarning yuzi ko‘zguda go‘zal ko‘rinadi, in’om va ehsonning go‘zalligi esa faqir va g‘ariblar ila bilinadi.”"""),
    IslamicQuotes("Hasan Basriy",
        """“Torlik-ziqnalik qilmanglar, aks holda sizlarga torlik qilinadi.”"""),
    IslamicQuotes("Abu Bakr Siddiq",
        """“Mol ziqnalarning, qurol qo‘rqoqlarning, rahbarlik zaiflarning qo‘liga tushsa, ishlar buziladi.”"""),
    IslamicQuotes("Sa’diy Sheroziy",
        """“Agar qaysi yerda g‘arib xo‘rlansa, o‘sha mamlakat tezda vayron bo‘lur.”"""),
    IslamicQuotes("Ali ibn Abu Tolib ",
        """“Muhtojga yordam berishni ertaga qoldirmang. Zero, sizga yoki unga ertaga nima bo‘lishini bilmaysiz.”"""),
    IslamicQuotes("Ali ibn Abu Tolib",
        """“Muhtojga yordam berishni ertaga qoldirmang. Zero, sizga yoki unga ertaga nima bo‘lishini bilmaysiz.”"""),
  ];
}
